# Generated by Django 4.2.7 on 2024-02-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('borrowing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover', models.ImageField(blank=True, upload_to='books/media/uploads/')),
                ('review', models.TextField(blank=True, null=True)),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='users.useraccount')),
                ('category', models.ManyToManyField(to='categories.category')),
            ],
        ),
    ]
