"""Starter catalogue for a fresh library. Blurbs are original, short summaries."""

GENRES = [
    ("Fantasy", "🐉"), ("Science Fiction", "🚀"), ("Mystery & Thriller", "🔍"), ("Romance", "💞"),
    ("Literary Fiction", "🖋️"), ("Classics", "🏛️"), ("Historical Fiction", "🏰"), ("Horror", "👻"),
    ("Non-fiction", "📚"), ("Self-help", "🌱"), ("Humor", "😂"), ("Young Adult", "🎒"),
    ("Memoir", "🪞"), ("Magical Realism", "✨"),
]

MOODS = [
    ("Adventurous", "🧭"), ("Challenging", "🧗"), ("Dark", "🌑"), ("Emotional", "💧"), ("Funny", "😄"),
    ("Hopeful", "🌤️"), ("Informative", "💡"), ("Inspiring", "🔥"), ("Lighthearted", "🎈"),
    ("Mysterious", "🕵️"), ("Reflective", "🪞"), ("Relaxing", "☕"), ("Sad", "🥀"), ("Tense", "😰"),
    ("Romantic", "💌"),
]

# title, author, isbn13, year, pages, pace, fee, copies, genres, moods, teaser, description, featured
BOOKS = [
    ("The Hobbit", "J.R.R. Tolkien", "9780547928227", 1937, 300, "medium", "2.50", 4,
     ["Fantasy", "Classics"], ["Adventurous", "Lighthearted", "Hopeful"],
     "reluctant hero · dragons · second breakfast",
     "A comfort-loving homebody is swept out of his front door and into a treasure hunt with thirteen dwarves, a wizard and one very large dragon.", True),
    ("Dune", "Frank Herbert", "9780441172719", 1965, 658, "slow", "4.00", 3,
     ["Science Fiction", "Classics"], ["Adventurous", "Challenging", "Tense"],
     "desert planet · political chess · prophecy",
     "On a desert world that holds the most valuable substance in the universe, a young heir must survive betrayal and learn the ways of the people his family was sent to rule.", True),
    ("1984", "George Orwell", "9780451524935", 1949, 328, "medium", "2.00", 3,
     ["Classics", "Science Fiction"], ["Dark", "Challenging", "Reflective"],
     "surveillance · forbidden diary · rewriting history",
     "In a state where every screen watches back, a clerk who edits the past for a living begins to wonder what really happened.", False),
    ("To Kill a Mockingbird", "Harper Lee", "9780061120084", 1960, 336, "medium", "2.00", 3,
     ["Classics", "Literary Fiction"], ["Emotional", "Reflective", "Hopeful"],
     "small-town summer · courtroom · a father's courage",
     "Seen through a child's eyes, a Southern town is tested when a lawyer agrees to defend a man everyone has already judged.", False),
    ("Pride and Prejudice", "Jane Austen", "9780141439518", 1813, 480, "medium", "1.50", 3,
     ["Classics", "Romance"], ["Romantic", "Funny", "Lighthearted"],
     "witty banter · first impressions · ballroom drama",
     "A sharp-tongued second daughter and a proud, wealthy gentleman get each other spectacularly wrong — at first.", True),
    ("The Great Gatsby", "F. Scott Fitzgerald", "9780743273565", 1925, 180, "medium", "1.50", 2,
     ["Classics", "Literary Fiction"], ["Reflective", "Sad", "Romantic"],
     "jazz age parties · green light · old money",
     "A newcomer to Long Island is drawn into the glittering orbit of a mysterious millionaire who throws parties for one person who never comes.", False),
    ("The Midnight Library", "Matt Haig", "9780525559474", 2020, 304, "fast", "3.00", 3,
     ["Literary Fiction", "Magical Realism"], ["Hopeful", "Reflective", "Emotional"],
     "infinite shelves · second chances · what-ifs",
     "Between life and death there is a library, and every book is a version of your life you could have lived.", True),
    ("Project Hail Mary", "Andy Weir", "9780593135204", 2021, 496, "fast", "3.50", 3,
     ["Science Fiction"], ["Adventurous", "Funny", "Hopeful"],
     "amnesia in space · science problem-solving · unlikely friendship",
     "A lone astronaut wakes up light-years from home with no memory of why — and the fate of Earth depends on him figuring it out.", True),
    ("The Martian", "Andy Weir", "9780553418026", 2011, 384, "fast", "3.00", 2,
     ["Science Fiction", "Humor"], ["Funny", "Tense", "Adventurous"],
     "stranded · potatoes · duct tape",
     "Left for dead on Mars, an astronaut with a botany degree and a sarcastic streak sets out to survive until rescue is possible.", False),
    ("Gone Girl", "Gillian Flynn", "9780307588371", 2012, 432, "fast", "3.00", 2,
     ["Mystery & Thriller"], ["Dark", "Tense", "Mysterious"],
     "missing spouse · unreliable narrators · media circus",
     "On their fifth anniversary, a wife vanishes and her husband's story starts to crack under the public's gaze.", False),
    ("The Girl with the Dragon Tattoo", "Stieg Larsson", "9780307454546", 2005, 644, "medium", "3.00", 2,
     ["Mystery & Thriller"], ["Dark", "Mysterious", "Tense"],
     "cold case · island family · brilliant hacker",
     "A disgraced journalist and an uncompromising hacker investigate a decades-old disappearance inside a powerful Swedish family.", False),
    ("Sapiens", "Yuval Noah Harari", "9780062316097", 2011, 464, "medium", "3.50", 3,
     ["Non-fiction"], ["Informative", "Challenging", "Reflective"],
     "big history · shared myths · how we got here",
     "A sweeping tour of how an unremarkable ape came to rule the planet, told through the stories humans agree to believe.", False),
    ("Atomic Habits", "James Clear", "9780735211292", 2018, 320, "fast", "3.00", 4,
     ["Self-help", "Non-fiction"], ["Informative", "Inspiring", "Hopeful"],
     "tiny changes · systems over goals · 1% better",
     "A practical framework for building good habits and breaking bad ones by focusing on small, compounding changes.", True),
    ("Educated", "Tara Westover", "9780399590504", 2018, 352, "medium", "3.00", 2,
     ["Memoir", "Non-fiction"], ["Emotional", "Inspiring", "Reflective"],
     "mountain childhood · self-taught · finding a voice",
     "Raised off the grid without school, a young woman teaches herself enough to enter a classroom for the first time at seventeen.", False),
    ("The Alchemist", "Paulo Coelho", "9780062315007", 1988, 208, "fast", "2.00", 3,
     ["Literary Fiction", "Magical Realism"], ["Inspiring", "Hopeful", "Reflective"],
     "desert journey · recurring dream · omens",
     "A shepherd boy follows a dream across the desert in search of treasure and learns to listen to his heart.", False),
    ("Circe", "Madeline Miller", "9780316556347", 2018, 400, "medium", "3.00", 2,
     ["Fantasy", "Historical Fiction"], ["Emotional", "Reflective", "Adventurous"],
     "exiled goddess · witchcraft · myths retold",
     "Banished to an island, the overlooked daughter of the sun discovers the power of witchcraft and crosses paths with gods and heroes.", True),
    ("The Night Circus", "Erin Morgenstern", "9780307744432", 2011, 512, "slow", "3.00", 2,
     ["Fantasy", "Romance", "Magical Realism"], ["Mysterious", "Romantic", "Relaxing"],
     "black and white tents · rival magicians · open only at night",
     "A circus appears without warning, and inside it two young illusionists are bound to a contest neither fully understands.", False),
    ("The Name of the Wind", "Patrick Rothfuss", "9780756404741", 2007, 662, "slow", "3.50", 2,
     ["Fantasy"], ["Adventurous", "Mysterious", "Emotional"],
     "legendary innkeeper · magic university · story within a story",
     "A notorious hero, now hiding as an innkeeper, finally tells the true story of how he became a legend.", False),
    ("Mistborn: The Final Empire", "Brandon Sanderson", "9780765350381", 2006, 544, "fast", "3.00", 2,
     ["Fantasy"], ["Adventurous", "Tense", "Hopeful"],
     "ash falls · metal magic · impossible heist",
     "In a world where the dark lord won, a street thief joins a crew planning the ultimate heist: toppling an immortal emperor.", False),
    ("Six of Crows", "Leigh Bardugo", "9781627792127", 2015, 480, "fast", "3.00", 3,
     ["Fantasy", "Young Adult"], ["Adventurous", "Tense", "Funny"],
     "heist · found family · crooked canals",
     "Six outcasts with nothing to lose take on a job that could make them rich — if it doesn't get them killed first.", True),
    ("The Hitchhiker's Guide to the Galaxy", "Douglas Adams", "9780345391803", 1979, 224, "fast", "2.00", 3,
     ["Science Fiction", "Humor"], ["Funny", "Adventurous", "Lighthearted"],
     "towel · demolished planet · the number 42",
     "Seconds before Earth is bulldozed for a hyperspace bypass, an unremarkable man is whisked into the absurd wider galaxy.", False),
    ("Good Omens", "Terry Pratchett & Neil Gaiman", "9780060853983", 1990, 432, "medium", "2.50", 2,
     ["Fantasy", "Humor"], ["Funny", "Lighthearted", "Adventurous"],
     "angel and demon · misplaced antichrist · end of the world",
     "An angel and a demon who have grown fond of Earth team up to stop the apocalypse — mostly because they'd miss the restaurants.", False),
    ("Where the Crawdads Sing", "Delia Owens", "9780735219090", 2018, 384, "medium", "3.00", 2,
     ["Literary Fiction", "Mystery & Thriller"], ["Mysterious", "Emotional", "Reflective"],
     "marsh girl · nature · small-town trial",
     "A girl who raised herself in the North Carolina marshes becomes the prime suspect when a local golden boy is found dead.", False),
    ("The Seven Husbands of Evelyn Hugo", "Taylor Jenkins Reid", "9781501161933", 2017, 400, "fast", "3.00", 3,
     ["Historical Fiction", "Romance"], ["Emotional", "Romantic", "Reflective"],
     "old Hollywood · secrets · one true love",
     "A reclusive film icon finally tells her life story to an unknown journalist — and her reasons for choosing her are a mystery.", True),
    ("Normal People", "Sally Rooney", "9781984822185", 2018, 288, "medium", "2.50", 2,
     ["Literary Fiction", "Romance"], ["Emotional", "Romantic", "Sad"],
     "on-again off-again · small town to university · unsaid things",
     "Two teenagers from the same Irish town circle each other for years, never quite managing to say what they mean.", False),
    ("Rebecca", "Daphne du Maurier", "9780380730407", 1938, 416, "slow", "2.00", 2,
     ["Classics", "Mystery & Thriller"], ["Mysterious", "Dark", "Tense"],
     "grand estate · first wife's shadow · sinister housekeeper",
     "A young bride arrives at a vast English estate and finds herself haunted by the memory of her husband's first wife.", False),
    ("And Then There Were None", "Agatha Christie", "9780062073488", 1939, 272, "fast", "2.00", 3,
     ["Mystery & Thriller", "Classics"], ["Mysterious", "Tense", "Dark"],
     "island invitation · nursery rhyme · no one leaves",
     "Ten strangers are lured to an island, and one by one they begin to disappear.", False),
    ("The Silent Patient", "Alex Michaelides", "9781250301697", 2019, 336, "fast", "3.00", 2,
     ["Mystery & Thriller"], ["Mysterious", "Tense", "Dark"],
     "a painter who stopped speaking · therapist obsession · twist",
     "A famous painter shoots her husband and never speaks again; a psychotherapist becomes obsessed with uncovering why.", False),
    ("Klara and the Sun", "Kazuo Ishiguro", "9780593318171", 2021, 320, "slow", "3.00", 2,
     ["Science Fiction", "Literary Fiction"], ["Reflective", "Emotional", "Hopeful"],
     "observant narrator · devotion · what makes us human",
     "An artificial friend watches the world from a shop window, hoping to be chosen, and learns what love may require.", False),
    ("Frankenstein", "Mary Shelley", "9780486282114", 1818, 166, "medium", "1.50", 2,
     ["Classics", "Horror", "Science Fiction"], ["Dark", "Reflective", "Sad"],
     "arctic confession · ambition · a creation abandoned",
     "A young scientist succeeds in creating life and immediately flees from what he has made.", False),
    ("Dracula", "Bram Stoker", "9780486411095", 1897, 418, "medium", "1.50", 2,
     ["Classics", "Horror"], ["Dark", "Mysterious", "Tense"],
     "letters and diaries · castle in the mountains · garlic",
     "A solicitor's business trip to a remote castle sets off a chase across Europe against an ancient predator.", False),
    ("The Thursday Murder Club", "Richard Osman", "9781984880963", 2020, 384, "medium", "3.00", 2,
     ["Mystery & Thriller", "Humor"], ["Funny", "Mysterious", "Lighthearted"],
     "retirement village · amateur sleuths · cake",
     "Four residents of a retirement village meet weekly to discuss unsolved crimes — until a real one lands on their doorstep.", False),
    ("Anxious People", "Fredrik Backman", "9781501160837", 2019, 352, "medium", "3.00", 2,
     ["Literary Fiction", "Humor"], ["Funny", "Emotional", "Hopeful"],
     "botched robbery · open house · strangers",
     "A failed bank robber takes a group of strangers hostage at an apartment viewing, and nothing goes to plan for anyone.", False),
    ("A Man Called Ove", "Fredrik Backman", "9781476738024", 2012, 337, "medium", "2.50", 2,
     ["Literary Fiction", "Humor"], ["Emotional", "Funny", "Hopeful"],
     "grumpy neighbour · stray cat · rules",
     "A curmudgeon with strict routines finds his plans disrupted by chatty new neighbours who refuse to leave him alone.", False),
    ("Thinking, Fast and Slow", "Daniel Kahneman", "9780374533557", 2011, 512, "slow", "3.50", 2,
     ["Non-fiction"], ["Informative", "Challenging", "Reflective"],
     "two systems · biases · decisions",
     "A Nobel laureate explains the two systems that drive how we think, and the predictable ways they mislead us.", False),
    ("Quiet", "Susan Cain", "9780307352156", 2012, 368, "medium", "3.00", 2,
     ["Non-fiction", "Self-help"], ["Informative", "Reflective", "Inspiring"],
     "introverts · a world that can't stop talking · hidden strengths",
     "An exploration of introversion and how a culture that prizes being outgoing undervalues quiet people.", False),
    ("Kafka on the Shore", "Haruki Murakami", "9781400079278", 2002, 480, "slow", "3.00", 2,
     ["Magical Realism", "Literary Fiction"], ["Mysterious", "Reflective", "Challenging"],
     "runaway teen · talking cats · a library in the south",
     "A teenage runaway and an old man who can speak with cats are pulled toward each other along strange, dreamlike paths.", False),
    ("Norwegian Wood", "Haruki Murakami", "9780375704024", 1987, 296, "slow", "2.50", 2,
     ["Literary Fiction", "Romance"], ["Sad", "Reflective", "Romantic"],
     "1960s Tokyo · a Beatles song · first love and loss",
     "A song on a plane sends a man back to his student years and two women who changed him.", False),
    ("The Remains of the Day", "Kazuo Ishiguro", "9780679731726", 1989, 245, "slow", "2.50", 2,
     ["Literary Fiction", "Historical Fiction"], ["Reflective", "Sad", "Relaxing"],
     "English butler · road trip · things left unsaid",
     "On a rare holiday, a devoted butler looks back on decades of service and the life he chose not to live.", False),
    ("Neuromancer", "William Gibson", "9780441569595", 1984, 271, "fast", "2.50", 2,
     ["Science Fiction"], ["Dark", "Adventurous", "Challenging"],
     "cyberspace · washed-up hacker · neon cities",
     "A burned-out hacker is offered one last job that will take him deep into cyberspace and into the plans of an AI.", False),
    ("Brave New World", "Aldous Huxley", "9780060850524", 1932, 288, "medium", "2.00", 2,
     ["Classics", "Science Fiction"], ["Challenging", "Dark", "Reflective"],
     "engineered happiness · conditioning · an outsider",
     "In a future where everyone is engineered to be content, a man from the outside questions what has been traded away.", False),
    ("The Little Prince", "Antoine de Saint-Exupéry", "9780156012195", 1943, 96, "fast", "1.00", 3,
     ["Classics", "Fantasy"], ["Reflective", "Emotional", "Hopeful"],
     "stranded pilot · tiny planet · a rose",
     "A pilot stranded in the desert meets a small traveller from another planet with big questions about grown-ups.", False),
    ("Harry Potter and the Sorcerer's Stone", "J.K. Rowling", "9780590353427", 1997, 309, "fast", "2.50", 4,
     ["Fantasy", "Young Adult"], ["Adventurous", "Lighthearted", "Funny"],
     "letters by owl · boarding school · a hidden treasure",
     "On his eleventh birthday, a boy living under the stairs learns he has a place at a school of magic.", False),
    ("The Book Thief", "Markus Zusak", "9780375842207", 2005, 592, "medium", "3.00", 2,
     ["Historical Fiction", "Young Adult"], ["Emotional", "Sad", "Hopeful"],
     "unusual narrator · stolen books · a basement secret",
     "In wartime Germany, a foster girl steals books and shares them with neighbours and the man hidden in her basement.", False),
    ("Fahrenheit 451", "Ray Bradbury", "9781451673319", 1953, 256, "fast", "2.00", 2,
     ["Classics", "Science Fiction"], ["Dark", "Reflective", "Tense"],
     "firemen start fires · parlour walls · memory",
     "A fireman whose job is burning books begins to wonder what's inside them.", False),
    ("Tomorrow, and Tomorrow, and Tomorrow", "Gabrielle Zevin", "9780593321201", 2022, 416, "medium", "3.50", 2,
     ["Literary Fiction"], ["Emotional", "Reflective", "Inspiring"],
     "video games · creative partnership · decades of friendship",
     "Two friends who met as kids become game-design partners, building worlds together while their own friendship is tested.", True),
    ("Lessons in Chemistry", "Bonnie Garmus", "9780385547345", 2022, 400, "medium", "3.50", 2,
     ["Historical Fiction", "Humor"], ["Funny", "Inspiring", "Emotional"],
     "1960s lab · cooking show · rowing",
     "A brilliant chemist pushed out of her lab ends up hosting a TV cooking show and quietly teaching a nation to think.", False),
    ("Fourth Wing", "Rebecca Yarros", "9781649374042", 2023, 528, "fast", "3.50", 3,
     ["Fantasy", "Romance"], ["Adventurous", "Romantic", "Tense"],
     "war college · dragons choose riders · enemies to lovers",
     "A scholar is forced into a brutal academy for dragon riders where making it to graduation is the only goal.", False),
]
