# Generated by Django 4.2.7 on 2024-02-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0004_alter_book_borrowed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrow_timestamp', models.DateTimeField(auto_now_add=True)),
                ('return_timestamp', models.DateTimeField(blank=True)),
                ('borrowed_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='books.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='users.useraccount')),
            ],
        ),
    ]
