# Generated by Django 4.2.7 on 2024-02-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing_histories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='return_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
