# Generated by Django 4.2.7 on 2024-02-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='return_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
