# Generated by Django 4.2.7 on 2024-02-15 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('transactions', '0002_alter_transaction_return_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='borrowed_book',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Borrow', 'Borrow'), ('Return', 'Return')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='users.useraccount'),
        ),
    ]
