# Generated by Django 4.2.7 on 2024-02-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='book',
            new_name='borrowed_book',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='borrower',
        ),
    ]
