# Generated by Django 4.2.7 on 2024-02-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_book_reviews_borrowed_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='borrower',
            new_name='reviewer',
        ),
    ]
