# Generated by Django 4.2.7 on 2024-02-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('reviews', '0003_rename_borrower_reviews_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.useraccount'),
        ),
    ]
