# Generated by Django 5.2.17 on 2026-09-26 17:05

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("bio", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
                ("emoji", models.CharField(blank=True, max_length=8)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("emoji", models.CharField(blank=True, max_length=8)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=13, verbose_name="ISBN-13"),
                ),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
                (
                    "cover_url",
                    models.URLField(
                        blank=True, help_text="Leave empty to use Open Library by ISBN."
                    ),
                ),
                ("pages", models.PositiveIntegerField(default=0)),
                (
                    "published_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("language", models.CharField(default="English", max_length=30)),
                (
                    "pace",
                    models.CharField(
                        choices=[
                            ("slow", "Slow burn"),
                            ("medium", "Steady"),
                            ("fast", "Page-turner"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "borrowing_fee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.00"), max_digits=8
                    ),
                ),
                ("total_copies", models.PositiveSmallIntegerField(default=1)),
                (
                    "blind_date_teaser",
                    models.CharField(
                        blank=True,
                        help_text="Spoiler-free hints shown on Blind Date cards, e.g. 'heist · found family · rainy city'.",
                        max_length=160,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="catalog.author",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="books", to="catalog.genre"),
                ),
                (
                    "moods",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="catalog.mood"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                (
                    "chemistry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("true_love", "💘 True love"),
                            ("crush", "😊 Strong crush"),
                            ("complicated", "🤔 It's complicated"),
                            ("friend_zone", "🤝 Friend zone"),
                            ("no_chemistry", "🧊 No chemistry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contains_spoilers", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShelfItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelved_by",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="book",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="book_search_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("book", "user"), name="one_review_per_reader"
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("rating__gte", 1), ("rating__lte", 5)),
                name="rating_1_to_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="shelfitem",
            constraint=models.UniqueConstraint(
                fields=("user", "book"), name="unique_shelf_item"
            ),
        ),
    ]
